// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) return web;
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDTszWHMEMHY1Ed2ZftOcNUlvXl03S7g-k',
    appId: '1:823869540671:web:e642e9658a82b982feeb8a',
    messagingSenderId: '823869540671',
    projectId: 'ticketappflutter',
    authDomain: 'ticketappflutter.firebaseapp.com',
    storageBucket: 'ticketappflutter.appspot.com',
    measurementId: 'G-62RLP74TV0',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCdvEK2NYvZ6f9fwsDt6kSY3Ibx60GnibE',
    appId: '1:823869540671:android:8d411e855e0e16ddfeeb8a',
    messagingSenderId: '823869540671',
    projectId: 'ticketappflutter',
    storageBucket: 'ticketappflutter.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAjF92gRaTFJRTxk263fk6RXNowL7bVP00',
    appId: '1:823869540671:ios:62aa480e53147022feeb8a',
    messagingSenderId: '823869540671',
    projectId: 'ticketappflutter',
    storageBucket: 'ticketappflutter.appspot.com',
    androidClientId: '823869540671-ft6dvltju0uoed0mjp4br83rqihil2n5.apps.googleusercontent.com',
    iosClientId: '823869540671-72l3s0l6fm8fpljos6in1ava4s4pa2jt.apps.googleusercontent.com',
    iosBundleId: 'com.ferdidrgn.ticketapp',
  );
}
